# Generated by Django 5.2.7 on 2025-10-23 04:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("venue", "0002_alter_venue_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, editable=False)),
                (
                    "duration_hours",
                    models.PositiveSmallIntegerField(
                        help_text="Duration of the booking in hours.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="account.profile",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="venue.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("venue", "date", "start_time"),
                        name="unique_venue_date_start_time",
                    )
                ],
            },
        ),
    ]
